# Generated by Django 4.1.1 on 2023-03-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email_id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
