# Generated by Django 4.1.1 on 2023-03-31 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seller_rename_email_id_buyer_address'),
        ('accounts', '0003_remove_buyer_email_id_remove_seller_email_id_and_more'),
    ]

    operations = [
    ]
